### ISSUE TITLE
Translation unit's data type cannot be changed during edit or update.

### ISSUE THREAD

**Issue by VedantSahadeo** [perpetualintelligence/pidotapp-issues#30]
I can see the option to change the data type of a translation unit during edit, but as soon as I commit I get the following error.

![image](https://user-images.githubusercontent.com/62402148/81528129-d6c1b400-9310-11ea-9599-a3109fc60b49.png)

![image](https://user-images.githubusercontent.com/62402148/81528196-feb11780-9310-11ea-9874-f5db4764ead2.png)

**Comment by perpetualintelligence** [comment]
@VedantSahadeo thanks for reporting the issue. Added to Jun-2020 release plan.

**Comment by perpetualintelligence** [comment]
Fixed in v1. Data type for all translation units (except paragraphs, which is always string) can by changed now.
