### ISSUE TITLE
Translation unit's data type validation does not happen during create.

### ISSUE THREAD

**Issue by VedantSahadeo** [perpetualintelligence/pidotapp-issues#31]
I am selecting a data type , but on create or edit I can enter any value and its still accepting it ,against its data type, this behavior should not happen.

![image](https://user-images.githubusercontent.com/62402148/81528595-eab9e580-9311-11ea-9884-46755bda8fc0.png)

**Comment by perpetualintelligence** [comment]
@VedantSahadeo thanks for reporting the issue. Added to May-2020 release plan.

**Comment by perpetualintelligence** [comment]
Fixed in V1.  Translation unit api now validates the data type of source text suring create and update both.
