### ISSUE TITLE
Service not selected but Service Options are still available for Selection on the 'Select Subscription' page.

### ISSUE THREAD

**Issue by nehadgautam** [perpetualintelligence/pidotapp-issues#36]
On the 'Select Subscription' Page, all Service options are available for selection even when no Service  - Pi.Multilanguage() or Pi.Branding() is selected.
The Service options like 'Solo', 'Team' etc. should be unselected and grayed out until a Service is selected.
![Subscription](https://user-images.githubusercontent.com/65241627/81949284-4ccf5f00-9620-11ea-9c24-6c9e6d24d2c2.PNG)

**Comment by perpetualintelligence** [comment]
@nehadgautam Thanks for reporting the issue, since this a minor UI enhancement we have added this to our Jul-2020 release plan.

**Comment by perpetualintelligence** [comment]
Fixed in v1-may-2020. Scaling policy options are now visible if user selects a service.
