### ISSUE TITLE
When we dismiss an error message received on trying to add a Team member Email ID that does not exist in the system, User is not taken back to the 'Team' page.

### ISSUE THREAD

**Issue by nehadgautam** [perpetualintelligence/pidotapp-issues#41]
On Configurations > Team page, we can add new Team Members. When Email ID does not exist in the system, we receive an error message and the available options are 'Dismiss', 'Contact Support' and 'Report Bug'. When we choose to dismiss the error then ideally we should be taken back to the 'Team' Page but we are taken back to the Home page. Now, to add any Team member we need to navigate to  the 'Team' page again.

Step 1: Add an Email ID that does not exist in the system
![image](https://user-images.githubusercontent.com/65241627/82477574-4abc4300-9aed-11ea-9d81-22c05afe6ed6.png)

Step 2: Dismiss the error:
![image](https://user-images.githubusercontent.com/65241627/82477679-6aec0200-9aed-11ea-9336-51915d8def94.png)

User is taken to the Home screen.

**Comment by perpetualintelligence** [comment]
@nehadgautam thanks for reporting the issue, yes we can enhance this to add Go Back that will take the user to the last action before the error.

**Comment by perpetualintelligence** [comment]
The error page is now enhanced to have a Go Back button which takes the user to the last page which caused the error.

![image](https://user-images.githubusercontent.com/62374075/82981320-9add4e80-9fa0-11ea-8193-7f459fed6220.png)
