### ISSUE TITLE
Use of Translation states is not defined and is not restricted based on User Roles. All User Roles are given access to all the Translation states.

### ISSUE THREAD

**Issue by nehadgautam** [perpetualintelligence/pidotapp-issues#43]
Translation states are not defined/restricted based on Users Roles. Even a Contributor has access to all the Translation states. It is not clear how a Contributor will submit a Page for Review/Approval, How the Reviewers/Approvers/Translators will be notified of the Pages that need action from their end, How many levels of Review/Approvals are required, How the Contributors will be notified of the action taken on their pages, Which User Roles will get access to which Translation states? these points need to be addressed.

Translation states available for a Contributor:
![image](https://user-images.githubusercontent.com/65241627/82485377-fa4ae280-9af8-11ea-8e50-97f2714d7909.png)

**Comment by perpetualintelligence** [comment]
@nehadgautam , thanks for reporting an issue, however this is a designed behavior. Workflow state is a simple property on the page which can be modified by any user who has the write access on page. For e.g. a Contributor has write access and can modify page properties. You are requesting a change management and notification behavior for pages  which is currently not supported. In future we are planning to introduce workflow objects which will have change management, task management and notifications to reviewers. Closing this issue
